### ISSUE TITLE
ApiResource parameters denormalizationContext and normalizationContext doesn't affect

### ISSUE THREAD

**Issue by kadirov** [api-platform/api-platform#1892]
**API Platform version(s) affected**: 2.6.4
Everything ok when you downgrade to 2.6.3

**Description**  
ApiResource parameters denormalizationContext and normalizationContext doesn't affect.

**How to reproduce**  
In version 2.6.4 - swagger shows all fields and ignores denormalizationContext and normalizationContext
But In versions before that, for example 2.6.3 - everything is ok. Swagger shows considering   denormalizationContext and normalizationContext goups

How swagger looks with ApiPlatform version 2.6.3
![image](https://user-images.githubusercontent.com/4341071/115856226-a998e380-a445-11eb-8fd8-353b31a1aa53.png)

Same code with 2.6.4
![image](https://user-images.githubusercontent.com/4341071/115856342-cc2afc80-a445-11eb-8f65-b6cfff35629a.png)

Original file is there: https://github.com/kadirov/api-starter-kit/blob/master/src/Entity/User.php
```php

#[ApiResource(
    collectionOperations: [
        'get'                => [
            'security'              => "is_granted('ROLE_ADMIN')",
            'normalization_context' => ['groups' => ['users:read']],
        ],
        'post'               => [
            'controller' => UserCreateAction::class,
        ],
        'aboutMe'            => [
            'controller'      => UserAboutMeAction::class,
            'method'          => 'get',
            'path'            => 'users/about_me',
            'openapi_context' => [
                'summary'    => 'Shows info about the authenticated user',
            ],
        ],
        'auth'               => [
            'controller'      => UserAuthAction::class,
            'method'          => 'post',
            'path'            => 'users/auth',
            'openapi_context' => ['summary' => 'Authorization'],
        ],
        'authByRefreshToken' => [
            'controller'      => UserAuthByRefreshTokenAction::class,
            'method'          => 'post',
            'path'            => 'users/auth/refreshToken',
            'openapi_context' => ['summary' => 'Authorization by refreshToken'],
            'input'           => RefreshTokenRequestDto::class,
        ],
        'isUniqueEmail'      => [
            'controller'              => UserIsUniqueEmailAction::class,
            'method'                  => 'post',
            'path'                    => 'users/is_unique_email',
            'openapi_context'         => ['summary' => 'Checks email for uniqueness'],
            'denormalization_context' => ['groups' => ['user:isUniqueEmail:write']],
        ],
    ],
    itemOperations: [
        'changePassword' => [
            'controller'              => UserChangePasswordAction::class,
            'method'                  => 'put',
            'path'                    => 'users/{id}/password',
            'security'                => "object == user || is_granted('ROLE_ADMIN')",
            'openapi_context'         => ['summary' => 'Changes password'],
            'denormalization_context' => ['groups' => ['user:changePassword:write']],
        ],
        'delete'         => [
            'controller' => DeleteAction::class,
            'security'   => "object == user || is_granted('ROLE_ADMIN')",
        ],
        'get'            => [
            'security' => "object == user || is_granted('ROLE_ADMIN')",
        ],
        'put'            => [
            'security'                => "object == user || is_granted('ROLE_ADMIN')",
            'denormalization_context' => ['groups' => ['user:put:write']],
        ],
    ],
    denormalizationContext: ['groups' => ['user:write']],
    normalizationContext: ['groups' => ['user:read', 'users:read']],
)]
#[ApiFilter(OrderFilter::class, properties: ['id', 'createdAt', 'updatedAt', 'email'])]
#[ApiFilter(SearchFilter::class, properties: ['id' => 'exact', 'email' => 'partial'])]
#[UniqueEntity('email', message: 'This email is already used')]

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements
    UserInterface,
    UpdatedAtSettableInterface,
    CreatedAtSettableInterface,
    IsDeletedSettableInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    #[Groups(['users:read'])]
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    #[Assert\Email]
    #[Groups(['users:read', 'user:write', 'user:put:write', 'user:isUniqueEmail:write'])]
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    #[Groups(['user:write', 'user:changePassword:write'])]
    private $password;

    /**
     * @ORM\Column(type="array")
     */
    #[Groups(['user:read'])]
    private $roles = [];

    /**
     * @ORM\Column(type="datetime")
     */
    #[Groups(['user:read'])]
    private $createdAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     * @Groups({"user:read"})
     */
    #[Groups(['user:read'])]
    private $updatedAt;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isDeleted = false;

   // here getter and setter methods...
}
```

**Possible Solution**  
 Downgrade to 2.6.3

**Additional Context**  
Symfony version 5.2.6
PHP version 8.0.3
OS: tested on windows 10, Fedora 33, docker with Debian 10

**Comment by rabraghib** [comment]
I have the same issus, but if you checked the respenses schemas
`normalization_context`'s have been applied, Only `denormalizationContext`'s that dont work

**Comment by papylhomme** [comment]
Same problem here, downgrading to 2.6.3 works

**Comment by lebadapetru** [comment]
I feel a bit relieved that i'm not the only one facing this issue. i've opened a bug [here](https://github.com/api-platform/core/issues/4252#issuecomment-828327594) but i think it's the wrong place for it.

**Comment by papylhomme** [comment]
for what it's worth the controllers seem to be working just fine, the only real problem is the swagger UI displaying the wrong schema

**Comment by kadirov** [comment]
> for what it's worth the controllers seem to be working just fine, the only real problem is the swagger UI displaying the wrong schema

No, if you send for example password field which not showed in swagger then api-platfoem ignores it

**Comment by imsheng** [comment]
Same problem here

**Comment by aglou** [comment]
just to follow!

**Comment by miguelBarreiro85** [comment]
same problem

**Comment by weaverryan** [comment]
Btw, if anyone wants to do some digging, since the problem occurs between 2.6.3 and 2.6.4, here is the diff: https://github.com/api-platform/core/compare/v2.6.3...v2.6.4

From that diff, https://github.com/api-platform/core/pull/4138 looks particularly interesting. If someone having this issue could try to "revert" that PR manually on their local copy... to see if it makes any difference, that might help things :).

Cheers!

**Comment by guilliamxavier** [comment]
Indeed, several issues popped up after https://github.com/api-platform/core/pull/4138 (more precisely the commit ["Improve openapi performances"](https://github.com/api-platform/core/pull/4138/commits/e5cf715f8662509e0263cb859e27cb0070215863)), for which the latest fix is https://github.com/api-platform/core/pull/4247

**Comment by raph35** [comment]
> > for what it's worth the controllers seem to be working just fine, the only real problem is the swagger UI displaying the wrong schema
> 
> No, if you send for example password field which not showed in swagger then api-platfoem ignores it

Swagger display the wrong schema in the method but the controller still follow the right schema that is created with normalizationContext and denormalizationContext
(It seems that Swagger UI only display the wrong schema but the controllers still working and filter the data that have been posted

**Comment by Renrhaf** [comment]
Same issue here, everything still works fine in the backend but the Swagger/ReDoc is not using the denormalization context data to show the right parameters.

**Comment by rabraghib** [comment]
PS: v2.6.5 this is still not fixed

**Comment by guilliamxavier** [comment]
Then this might be related to https://github.com/api-platform/core/issues/4248 (or not)

**Comment by kadirov** [comment]
> PS: v2.6.5 this is still not fixed

How they not see yet this bug?

**Comment by alanpoulain** [comment]
I don't see the bug anymore in 2.6.5.
@kadirov if I take your example.

**2.6.4**
![image](https://user-images.githubusercontent.com/10920253/123073221-845d2d00-d416-11eb-8a25-c4b5f366bbaa.png)

**2.6.5**
![image](https://user-images.githubusercontent.com/10920253/123073327-9b038400-d416-11eb-8b74-0a8009b47218.png)

**Comment by botris** [comment]
@alanpoulain I can confirm that the different issues I had  around this problem have been fixed in 2.6.5

**Comment by rabraghib** [comment]
@alanpoulain I just setup new app but it hasn't been fixed 😕
![Screenshot 2021-06-23 104837](https://user-images.githubusercontent.com/49442862/123076560-2bd76100-d411-11eb-8a0c-47bdb07b674a.png)

Here is the entity code
```php
// App\Entity\Test

// .....

**
 * @ORM\Entity(repositoryClass=TestRepository::class)
 */
#[ApiResource(
    collectionOperations: ['get','post'],
    itemOperations: [
        'patch' => [
            'denormalization_context' => ['groups' => ['write']]
        ]
    ],
    denormalizationContext: ['groups' => ['create']],
    normalizationContext: ['groups' => ['read']],
)]
class Test
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    #[Groups(['read'])]
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    #[Groups(['read','create','write'])]
    private $prop1;

    /**
     * @ORM\Column(type="string", length=255)
     */
    #[Groups(['create','write'])]
    private $prop2;

    /**
     * @ORM\Column(type="string", length=255)
     */
    #[Groups(['write'])]
    private $prop3;

    // ....
}
```

**Comment by alanpoulain** [comment]
@rabraghib
![image](https://user-images.githubusercontent.com/10920253/123079194-fd12b800-d41b-11eb-978d-7a3ab4edb8c3.png)

Please make sure:
- Your entity has getters for your private properties:
```php
    public function getId(): int
    {
        return $this->id;
    }

    public function getProp1(): string
    {
        return $this->prop1;
    }

    public function getProp2(): string
    {
        return $this->prop2;
    }

    public function getProp3(): string
    {
        return $this->prop3;
    }
```
- You are using the last version of `api-platform/core`:
`docker-compose exec php composer req api-platform/core:^2.6.5`

**Comment by rabraghib** [comment]
@alanpoulain yes it has getter & setter and I am using latest symfony version and version 2.6.5 of api platform

**Comment by alanpoulain** [comment]
Make sure you cache is cleared.
Something is wrong in your project, you can try it on a new project, you will see that the issue is gone.

**Comment by rabraghib** [comment]
that is a new project 😕
but if it has been fixed thanks I'll figure out where is the problem

**Comment by kadirov** [comment]
I've tested. Problem solved in 2.6.5!
Thank you all !!!

**Comment by rabraghib** [comment]
thanks @alanpoulain its fixed as you said 👍

**Comment by jeanatpi** [comment]
Still have an issue with this example on Symfony 6 and version 2.6.8:

`<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\CheeseListingRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Serializer\Annotation\SerializedName;

#[ORM\Entity(repositoryClass: CheeseListingRepository::class)]
#[ApiResource(
    shortName: "cheeses",
    denormalizationContext: ['groups' => ['write']],
    normalizationContext: ['groups' => ['read']],
)]
class CheeseListing
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Groups(["read","write"])]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Groups(["read"])]
    private ?string $description = null;

    #[ORM\Column]
    #[Groups(["read","write"])]
    private ?int $price = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column]
    private bool $isPublished = false;

    public function __construct()
    {
        $this->createdAt = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }


    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;
        return $this;
    }

    #[Groups("write")]
    public function setTextDescription(string $description): self
    {
        $this->description = nl2br($description);
        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    #[Groups("read")]
    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function isIsPublished(): ?bool
    {
        return $this->isPublished;
    }


    public function setIsPublished(bool $isPublished): self
    {
        $this->isPublished = $isPublished;

        return $this;
    }
}
`

**Comment by etal0n** [comment]
> Still have an issue with this example on Symfony 6 and version 2.6.8.

3.0 rc2 also
