### ISSUE TITLE
Looks like composer dev requirements block creating the project via 'composer create-project' for PHP version 7.x

### ISSUE THREAD

**Issue by tekmi** [api-platform/api-platform#42]
Problem 1
    - Installation request for behatch/contexts dev-master -> satisfiable by behatch/contexts[dev-master].
    - behatch/contexts dev-master requires php ~5.4 -> your PHP version (7.0.2-4+deb.sury.org~trusty+1)

Easily solved by: composer create-project api-platform/api-platform customer-directory-api --no-dev though, but I guess would be nicer to be able to have all dependencies.

**Comment by dunglas** [comment]
Thanks for the report.

The upcoming API Platform 1.1 will be compliant with both PHP 7 and and Symfony 3. We are just waiting for https://github.com/minkphp/Mink/issues/685 to be fixed for releasing it.

**Comment by jdgriffith** [comment]
Still experiencing this issue.

```

  Problem 1
    - Installation request for behatch/contexts dev-master -> satisfiable by behatch/contexts[dev-master].
    - behatch/contexts dev-master requires php ~5.4 -> your PHP version (7.0.2) does not satisfy that requirement.
```

**Comment by dunglas** [comment]
Works now:

    composer create-project api-platform/api-platform:dev-master demo

**Comment by luispabon** [comment]
That mink issue was fixed; what's the progress of 1.1? I feel dirty when requiring dev-master deps.

**Comment by WitteStier** [comment]
I still have this issue. Please mention `:dev-master` in the get started page.
